import type {
  ModelCatalogItem,
  ModelCatalogProvider,
  ModelCatalogSnapshot,
} from "../../types";

export const previewProviders: ModelCatalogProvider[] = [
  { id: "openai", name: "OpenAI", api: "https://api.openai.com/v1", doc: "https://platform.openai.com/docs", tier: "lab", subscription: false, count: 258, dateModified: "2026-08-17", isFirstParty: true },
  { id: "anthropic", name: "Anthropic", api: "https://api.anthropic.com/v1", doc: "https://docs.anthropic.com", tier: "lab", subscription: false, count: 179, dateModified: "2026-08-17", isFirstParty: true },
  { id: "google", name: "Google", api: null, doc: "https://ai.google.dev", tier: "lab", subscription: false, count: 162, dateModified: "2026-08-17", isFirstParty: true },
  { id: "deepseek", name: "DeepSeek", api: "https://api.deepseek.com", doc: "https://api-docs.deepseek.com", tier: "lab", subscription: false, count: 92, dateModified: "2026-08-17", isFirstParty: true },
  { id: "openrouter", name: "OpenRouter", api: "https://openrouter.ai/api/v1", doc: "https://openrouter.ai/docs", tier: "gateway", subscription: false, count: 320, dateModified: "2026-08-17", isFirstParty: false },
  { id: "deepinfra", name: "Deep Infra", api: null, doc: "https://deepinfra.com", tier: "cloud", subscription: false, count: 58, dateModified: "2026-08-17", isFirstParty: false },
  { id: "siliconflow", name: "SiliconFlow", api: "https://api.siliconflow.cn/v1", doc: "https://docs.siliconflow.cn", tier: "cloud", subscription: false, count: 110, dateModified: "2026-08-17", isFirstParty: false },
  { id: "nano-gpt", name: "NanoGPT", api: "https://nano-gpt.com/api/v1", doc: "https://docs.nano-gpt.com", tier: "gateway", subscription: false, count: 601, dateModified: "2026-08-17", isFirstParty: false },
];

export const previewModels: ModelCatalogItem[] = [
  {
    id: "openai/gpt-5-turbo",
    slug: "gpt5turbo",
    name: "GPT-5 Turbo",
    lab: "openai",
    kind: "text",
    family: "gpt-5",
    knowledge: "2025-12",
    status: "ga",
    openWeights: false,
    reasoning: true,
    toolCall: true,
    attachment: true,
    structured: true,
    temperature: true,
    inputModalities: ["text", "image", "audio", "video", "pdf"],
    contextLength: 256_000,
    contextMin: 128_000,
    contextMax: 256_000,
    maxOutputTokens: 32_768,
    refProvider: "openai",
    refOfficial: true,
    refInputCost: 1.5,
    refOutputCost: 6.0,
    refCacheReadCost: 0.375,
    minProvider: "openrouter",
    minInputCost: 1.25,
    minOutputCost: 5.0,
    minCacheReadCost: 0.3,
    priceSpread: 1.2,
    blendedMin: 2.18,
    blendedTrusted: 2.62,
    blendedRef: 2.625,
    hostCount: 28,
    pricedHostCount: 24,
    freeHostCount: 2,
    subHostCount: 2,
    hostProviders: ["openai", "openrouter", "deepinfra", "nano-gpt"],
    aaIdx: 94.2,
    aaCoding: 96.5,
    aaAgentic: 92.1,
    aaSpeed: 112.0,
    aaTtft: 0.65,
    aaTaskCost: 0.182,
    benchmarkCount: 35,
    releaseDate: "2026-04-10",
    lastUpdated: "2026-08-17",
    officialLab: "openai",
    officialModelId: "gpt-5-turbo",
    canonicalId: null,
    identitySource: "llmpricing_lab",
    identityResolved: true,
    officialHostCount: 1,
    officialChannelProviders: ["openai"],
    labTierHostCount: 1,
    cloudTierHostCount: 1,
    gatewayTierHostCount: 2,
    freeChannelCount: 2,
    freeChannelProviders: ["deepinfra", "nano-gpt"],
    subscriptionChannelProviders: [],
    freeChannelSource: "derived",
    freeChannelCountMatches: true,
    reasoningOptions: [{ kind: "effort", values: ["low", "medium", "high", "xhigh"] }],
    reasoningEffortMax: "xhigh",
    interleavedFields: ["reasoning_details"],
    hasFastMode: true,
    outputModalities: ["text", "image"],
    maxInputTokens: 128_000,
  },
  {
    id: "anthropic/claude-3-7-sonnet",
    slug: "claude37sonnet",
    name: "Claude 3.7 Sonnet",
    lab: "anthropic",
    kind: "text",
    family: "claude-sonnet",
    knowledge: "2026-02",
    status: "ga",
    openWeights: false,
    reasoning: true,
    toolCall: true,
    attachment: true,
    structured: true,
    temperature: true,
    inputModalities: ["text", "image", "pdf"],
    contextLength: 200_000,
    contextMin: 200_000,
    contextMax: 200_000,
    maxOutputTokens: 64_000,
    refProvider: "anthropic",
    refOfficial: true,
    refInputCost: 3.0,
    refOutputCost: 15.0,
    refCacheReadCost: 0.3,
    minProvider: "kilo",
    minInputCost: 2.7,
    minOutputCost: 13.5,
    minCacheReadCost: 0.27,
    priceSpread: 1.11,
    blendedMin: 5.4,
    blendedTrusted: 6.0,
    blendedRef: 6.0,
    hostCount: 35,
    pricedHostCount: 32,
    freeHostCount: 1,
    subHostCount: 2,
    hostProviders: ["anthropic", "openrouter", "nano-gpt", "deepinfra"],
    aaIdx: 96.8,
    aaCoding: 98.2,
    aaAgentic: 95.4,
    aaSpeed: 88.0,
    aaTtft: 0.82,
    aaTaskCost: 0.245,
    benchmarkCount: 42,
    releaseDate: "2026-02-24",
    lastUpdated: "2026-08-17",
    officialLab: "anthropic",
    officialModelId: "claude-3-7-sonnet",
    canonicalId: null,
    identitySource: "llmpricing_lab",
    identityResolved: true,
    officialHostCount: 1,
    officialChannelProviders: ["anthropic"],
    labTierHostCount: 1,
    cloudTierHostCount: 1,
    gatewayTierHostCount: 2,
    freeChannelCount: 1,
    freeChannelProviders: ["openrouter"],
    subscriptionChannelProviders: ["nano-gpt", "deepinfra"],
    freeChannelSource: "derived",
    freeChannelCountMatches: true,
  },
  {
    id: "deepseek/deepseek-r1",
    slug: "deepseekr1",
    name: "DeepSeek R1",
    lab: "deepseek",
    kind: "text",
    family: "deepseek-r1",
    knowledge: "2024-12",
    status: "ga",
    openWeights: true,
    reasoning: true,
    toolCall: true,
    attachment: false,
    structured: true,
    temperature: true,
    inputModalities: ["text"],
    contextLength: 128_000,
    contextMin: 64_000,
    contextMax: 128_000,
    maxOutputTokens: 32_768,
    refProvider: "deepseek",
    refOfficial: true,
    refInputCost: 0.55,
    refOutputCost: 2.19,
    refCacheReadCost: 0.14,
    minProvider: "siliconflow",
    minInputCost: 0.28,
    minOutputCost: 1.10,
    minCacheReadCost: 0.07,
    priceSpread: 2.0,
    blendedMin: 0.485,
    blendedTrusted: 0.96,
    blendedRef: 0.96,
    hostCount: 56,
    pricedHostCount: 48,
    freeHostCount: 4,
    subHostCount: 4,
    hostProviders: ["deepseek", "siliconflow", "openrouter", "deepinfra", "nano-gpt"],
    aaIdx: 91.5,
    aaCoding: 94.0,
    aaAgentic: 88.6,
    aaSpeed: 64.0,
    aaTtft: 1.12,
    aaTaskCost: 0.089,
    benchmarkCount: 30,
    releaseDate: "2025-01-20",
    lastUpdated: "2026-08-17",
    officialLab: "deepseek",
    officialModelId: "deepseek-r1",
    canonicalId: null,
    identitySource: "llmpricing_lab",
    identityResolved: true,
    officialHostCount: 1,
    officialChannelProviders: ["deepseek"],
    labTierHostCount: 1,
    cloudTierHostCount: 2,
    gatewayTierHostCount: 2,
    freeChannelCount: 3,
    freeChannelProviders: ["openrouter", "deepinfra", "nano-gpt"],
    subscriptionChannelProviders: [],
    freeChannelSource: "derived",
    freeChannelCountMatches: true,
    reasoningOptions: [{ kind: "effort", values: ["low", "medium", "high"] }],
    reasoningEffortMax: "high",
    interleavedFields: ["reasoning_content"],
  },
  {
    id: "zhipuai/glm-5.2",
    slug: "glm52",
    name: "GLM-5.2",
    lab: "zhipuai",
    kind: "text",
    family: "glm",
    knowledge: "2026-05",
    status: "ga",
    openWeights: true,
    reasoning: true,
    toolCall: true,
    attachment: false,
    structured: true,
    temperature: true,
    inputModalities: ["text", "image"],
    contextLength: 1_000_000,
    contextMin: 96_000,
    contextMax: 1_049_000,
    maxOutputTokens: 131_072,
    refProvider: "zai",
    refOfficial: true,
    refInputCost: 1.4,
    refOutputCost: 4.4,
    refCacheReadCost: 0.26,
    minProvider: "nano-gpt",
    minInputCost: 0.42,
    minOutputCost: 1.32,
    minCacheReadCost: 0.078,
    priceSpread: 5.5,
    blendedMin: 0.645,
    blendedTrusted: 1.075,
    blendedRef: 2.15,
    hostCount: 80,
    pricedHostCount: 69,
    freeHostCount: 3,
    subHostCount: 6,
    hostProviders: ["zai", "siliconflow", "openrouter", "nano-gpt", "deepinfra"],
    aaIdx: 52.6,
    aaCoding: 68.8,
    aaAgentic: 45.7,
    aaSpeed: 139.0,
    aaTtft: 1.37,
    aaTaskCost: 0.3206,
    benchmarkCount: 19,
    releaseDate: "2026-06-13",
    lastUpdated: "2026-08-17",
    officialLab: "zhipuai",
    officialModelId: "glm-5.2",
    canonicalId: null,
    identitySource: "llmpricing_lab",
    identityResolved: true,
    officialHostCount: 0,
    officialChannelProviders: [],
    labTierHostCount: 0,
    cloudTierHostCount: 2,
    gatewayTierHostCount: 2,
    freeChannelCount: 3,
    freeChannelProviders: ["siliconflow", "openrouter", "deepinfra"],
    subscriptionChannelProviders: [],
    freeChannelSource: "derived",
    freeChannelCountMatches: true,
    reasoningOptions: [{ kind: "effort", values: ["none", "minimal", "low", "medium", "high", "xhigh", "max"] }],
    reasoningEffortMax: "max",
    interleavedFields: ["reasoning_content"],
    maxInputTokens: 272_000,
  },
  {
    id: "google/gemini-3-pro-image",
    slug: "gemini3proimage",
    name: "Gemini 3 Pro Image",
    lab: "google",
    kind: "image",
    family: "gemini-pro",
    knowledge: "2025-01",
    status: "ga",
    openWeights: false,
    reasoning: true,
    toolCall: false,
    attachment: true,
    structured: true,
    temperature: true,
    inputModalities: ["text", "image", "pdf"],
    contextLength: 65_536,
    contextMin: 65_536,
    contextMax: 131_072,
    maxOutputTokens: 32_768,
    refProvider: "google",
    refOfficial: true,
    refInputCost: 1.25,
    refOutputCost: 5.0,
    refCacheReadCost: 0.31,
    minProvider: "openrouter",
    minInputCost: 1.0,
    minOutputCost: 4.0,
    minCacheReadCost: 0.25,
    priceSpread: 1.25,
    blendedMin: 1.75,
    blendedTrusted: 2.18,
    blendedRef: 2.18,
    hostCount: 12,
    pricedHostCount: 10,
    freeHostCount: 1,
    subHostCount: 1,
    hostProviders: ["google", "openrouter"],
    aaIdx: null,
    aaCoding: null,
    aaAgentic: null,
    aaSpeed: null,
    aaTtft: null,
    aaTaskCost: null,
    benchmarkCount: 0,
    releaseDate: "2026-03-15",
    lastUpdated: "2026-08-17",
    officialLab: "google",
    officialModelId: "gemini-3-pro-image",
    canonicalId: null,
    identitySource: "llmpricing_lab",
    identityResolved: true,
    officialHostCount: 1,
    officialChannelProviders: ["google"],
    labTierHostCount: 1,
    cloudTierHostCount: 0,
    gatewayTierHostCount: 1,
    freeChannelCount: 0,
    freeChannelProviders: [],
    subscriptionChannelProviders: [],
    freeChannelSource: "derived",
    freeChannelCountMatches: true,
  },
  {
    id: "alibaba/qwen3-embedding-8b",
    slug: "qwen3embedding8b",
    name: "Qwen3-Embedding-8B",
    lab: "alibaba",
    kind: "embedding",
    family: "qwen",
    knowledge: "2024-12",
    status: "ga",
    openWeights: true,
    reasoning: false,
    toolCall: false,
    attachment: false,
    structured: false,
    temperature: false,
    inputModalities: ["text"],
    contextLength: 40_960,
    contextMin: 32_000,
    contextMax: 40_960,
    maxOutputTokens: 4_096,
    refProvider: "alibaba",
    refOfficial: true,
    refInputCost: 0.05,
    refOutputCost: 0,
    refCacheReadCost: 0,
    minProvider: "siliconflow",
    minInputCost: 0.02,
    minOutputCost: 0,
    minCacheReadCost: 0,
    priceSpread: 2.5,
    blendedMin: 0.015,
    blendedTrusted: 0.035,
    blendedRef: 0.035,
    hostCount: 18,
    pricedHostCount: 15,
    freeHostCount: 2,
    subHostCount: 1,
    hostProviders: ["alibaba", "siliconflow", "deepinfra"],
    aaIdx: null,
    aaCoding: null,
    aaAgentic: null,
    aaSpeed: null,
    aaTtft: null,
    aaTaskCost: null,
    benchmarkCount: 0,
    releaseDate: "2025-06-20",
    lastUpdated: "2026-08-17",
    officialLab: "alibaba",
    officialModelId: "qwen3-embedding-8b",
    canonicalId: null,
    identitySource: "llmpricing_lab",
    identityResolved: true,
    officialHostCount: 0,
    officialChannelProviders: [],
    labTierHostCount: 0,
    cloudTierHostCount: 2,
    gatewayTierHostCount: 0,
    freeChannelCount: 1,
    freeChannelProviders: ["deepinfra"],
    subscriptionChannelProviders: [],
    freeChannelSource: "derived",
    freeChannelCountMatches: true,
  },
  {
    // 白牌 / 路由类模型的预览样本：原始厂商无法确定，系统**刻意不猜**，
    // 保留 `misc` 并置 identityResolved = false。真实数据里这类模型有 72 个
    // （如 `auto`、`model-router`、`claw-*`、`code-*`）。
    id: "misc/model-router-pro",
    slug: "modelrouterpro",
    name: "Model Router Pro",
    lab: "misc",
    kind: "text",
    family: null,
    knowledge: "2025-10",
    status: "ga",
    openWeights: false,
    reasoning: true,
    toolCall: true,
    attachment: false,
    structured: true,
    temperature: true,
    inputModalities: ["text"],
    contextLength: 200_000,
    contextMin: 32_000,
    contextMax: 200_000,
    maxOutputTokens: 16_384,
    refProvider: "openrouter",
    refOfficial: false,
    refInputCost: 0.9,
    refOutputCost: 3.2,
    refCacheReadCost: 0.18,
    minProvider: "nano-gpt",
    minInputCost: 0.62,
    minOutputCost: 2.1,
    minCacheReadCost: 0.12,
    priceSpread: 1.45,
    blendedMin: 0.99,
    blendedTrusted: 1.18,
    blendedRef: 1.48,
    hostCount: 4,
    pricedHostCount: 3,
    freeHostCount: 1,
    subHostCount: 0,
    hostProviders: ["openrouter", "nano-gpt", "deepinfra", "siliconflow"],
    aaIdx: null,
    aaCoding: null,
    aaAgentic: null,
    aaSpeed: null,
    aaTtft: null,
    aaTaskCost: null,
    benchmarkCount: 0,
    releaseDate: "2025-10-02",
    lastUpdated: "2026-08-17",
    // 身份未确定：lab 保持 misc，不臆造厂商
    officialLab: "misc",
    officialModelId: "model-router-pro",
    canonicalId: null,
    identitySource: "unknown",
    identityResolved: false,
    officialHostCount: 0,
    officialChannelProviders: [],
    labTierHostCount: 0,
    cloudTierHostCount: 1,
    gatewayTierHostCount: 3,
    freeChannelCount: 1,
    freeChannelProviders: ["deepinfra"],
    subscriptionChannelProviders: [],
    freeChannelSource: "derived",
    freeChannelCountMatches: true,
  },
];

export const previewGeneratedModels: ModelCatalogItem[] = Array.from({ length: 94 }, (_, index) => {
  const labs = ["openai", "anthropic", "google", "deepseek", "alibaba", "zhipuai", "mistral", "meta"];
  const lab = labs[index % labs.length];
  const kinds = ["text", "text", "text", "image", "video", "audio", "embedding", "rerank"];
  const kind = kinds[index % kinds.length];
  const costIn = Number((((index % 9) + 1) * 0.25).toFixed(3));
  const costOut = kind === "embedding" || kind === "rerank" ? 0 : Number((costIn * 3.5).toFixed(3));

  return {
    id: `${lab}/model-preview-${index + 1}`,
    slug: `modelpreview${index + 1}`,
    name: `${lab.toUpperCase()} Model ${index + 1}`,
    lab,
    kind,
    family: `${lab}-gen`,
    knowledge: "2025-06",
    status: index % 15 === 0 ? "beta" : index % 25 === 0 ? "deprecated" : "ga",
    openWeights: index % 2 === 0,
    reasoning: index % 3 === 0,
    toolCall: kind === "text",
    attachment: kind === "text" || kind === "image",
    structured: kind === "text",
    temperature: kind === "text",
    inputModalities: ["text"],
    contextLength: 32_000 * ((index % 8) + 1),
    contextMin: 32_000,
    contextMax: 32_000 * ((index % 8) + 1),
    maxOutputTokens: 8_192 * ((index % 4) + 1),
    refProvider: lab,
    refOfficial: true,
    refInputCost: costIn,
    refOutputCost: costOut,
    refCacheReadCost: Number((costIn * 0.2).toFixed(4)),
    minProvider: "nano-gpt",
    minInputCost: Number((costIn * 0.7).toFixed(3)),
    minOutputCost: Number((costOut * 0.7).toFixed(3)),
    minCacheReadCost: Number((costIn * 0.15).toFixed(4)),
    priceSpread: 1.43,
    blendedMin: Number((costIn * 0.75).toFixed(3)),
    blendedTrusted: Number((costIn * 0.9).toFixed(3)),
    blendedRef: costIn,
    hostCount: ((index % 20) + 2) * 3,
    pricedHostCount: ((index % 18) + 2) * 2,
    freeHostCount: index % 4 === 0 ? 2 : 0,
    subHostCount: index % 5 === 0 ? 1 : 0,
    hostProviders: [lab, "openrouter", "deepinfra", "nano-gpt", "siliconflow"],
    aaIdx: index % 4 === 0 ? 70 + (index % 25) : null,
    aaCoding: index % 4 === 0 ? 72 + (index % 25) : null,
    aaAgentic: index % 4 === 0 ? 68 + (index % 25) : null,
    aaSpeed: index % 4 === 0 ? 80 + (index % 60) : null,
    aaTtft: index % 4 === 0 ? 0.7 + ((index % 10) * 0.1) : null,
    aaTaskCost: index % 4 === 0 ? 0.1 + ((index % 5) * 0.05) : null,
    benchmarkCount: index % 4 === 0 ? 15 : 0,
    releaseDate: "2025-11-10",
    lastUpdated: "2026-08-17",
    // —— 身份与渠道分层（全部按 index 动态生成，勿写成常量）——
    officialLab: lab,
    officialModelId: `model-preview-${index + 1}`,
    canonicalId: null,
    identitySource: "llmpricing_lab",
    identityResolved: true,
    // hostProviders 里有 lab 自身，故官方渠道即 lab
    officialHostCount: 1,
    officialChannelProviders: [lab],
    // tier 三分之和应等于 hostProviders.length（5）
    labTierHostCount: 1,
    cloudTierHostCount: 2,
    gatewayTierHostCount: 2,
    // 免费渠道需排除原厂与最低价渠道（nano-gpt），否则会与「最低价」自相矛盾
    freeChannelCount: index % 4 === 0 ? 2 : 0,
    freeChannelProviders: index % 4 === 0 ? ["deepinfra", "siliconflow"] : [],
    subscriptionChannelProviders: index % 5 === 0 ? ["openrouter"] : [],
    freeChannelSource: "derived",
    freeChannelCountMatches: true,
  };
});

export const allPreviewModels = [...previewModels, ...previewGeneratedModels];

export const previewModelSnapshot: ModelCatalogSnapshot = {
  models: allPreviewModels,
  providers: previewProviders,
  total: allPreviewModels.length,
  lastSyncedAt: new Date().toISOString(),
  syncedToday: true,
  sources: [
    // 主数据源：模型身份 + 渠道明细 + 官方判定
    { source: "models_dev_catalog", url: "https://models.dev/catalog.json", fetchedAt: new Date().toISOString(), recordCount: 395 },
    { source: "llmpricing_manifest", url: "https://llmpricing.dev/rows/manifest.json", fetchedAt: new Date().toISOString(), recordCount: previewProviders.length },
    { source: "rows-000.json", url: "https://llmpricing.dev/rows/rows-000.json", fetchedAt: new Date().toISOString(), recordCount: 400 },
    { source: "rows-001.json", url: "https://llmpricing.dev/rows/rows-001.json", fetchedAt: new Date().toISOString(), recordCount: 400 },
    { source: "rows-002.json", url: "https://llmpricing.dev/rows/rows-002.json", fetchedAt: new Date().toISOString(), recordCount: 400 },
    { source: "rows-003.json", url: "https://llmpricing.dev/rows/rows-003.json", fetchedAt: new Date().toISOString(), recordCount: 400 },
    { source: "rows-004.json", url: "https://llmpricing.dev/rows/rows-004.json", fetchedAt: new Date().toISOString(), recordCount: 341 },
  ],
  meta: {
    syncedAt: new Date().toISOString(),
    providers: previewProviders.length,
    models: allPreviewModels.length,
    source: "https://models.dev",
  },
};
